
spring:
  application:
    name: customer-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/barakah_customer
    username: customer_user
    password: customer_pass

server:
  port: 8081

grpc:
  server:
    port: 9092

barakah:
  sharia:
    compliance-check: true
    auto-screening: true
  
  customer:
    kyc:
      required: true
      verification-levels: 3