# spring:
#     grpc:
#         server:
#             security:
#                 enabled: false
#     cloud:
#         kubernetes:
#             discovery:
#                 enabled: true
#                 all-namespaces: false
#                 namespace: barakah-fund

#     jackson:
#         serialization:
#             write-dates-as-timestamps: false
#         deserialization:
#             adjust-dates-to-context-time-zone: false
#         default-property-inclusion: non_null
#         #     fail-on-unknown-properties: false
#         #     fail-on-null-for-primitives: false
#         #     fail-on-numbers-for-enums: false
#         # default-property-inclusion: non_null
#         # mapper:
#         #     accept-case-insensitive-enums: true
#         # time-zone: UTC

#     cache:
#         type: redis
#         redis:
#             time-to-live: 3600000
#             cache-null-values: false

# grpc:
#     client:
#         account-service:
#             address: static://account-service:9092
#             negotiationType: PLAINTEXT
#             enableKeepAlive: true
#             keepAliveTime: 30s
#             keepAliveTimeout: 5s
#             keepAliveWithoutCalls: true
#             maxRetryAttempts: 3
#             security:
#                 enabled: false
#     server:
#         port: 9090
#         enableReflection: true
#         security:
#             enabled: false

# logging:
#     level:
#         com.barakah: DEBUG
#         net.devh.boot.grpc: DEBUG
#         io.grpc: DEBUG
