{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "barakah-fund.fullname" . }}-redis
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "barakah-fund.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "barakah-fund.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_REPLICATION_MODE
              value: master
          {{- if .Values.redis.auth.enabled }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password | quote }}
          {{- end }}
          command:
            - redis-server
            - --maxmemory
            - {{ .Values.redis.config.maxmemory | quote }}
            - --maxmemory-policy
            - {{ .Values.redis.config.maxmemoryPolicy | quote }}
            - --notify-keyspace-events
            - {{ .Values.redis.config.notifyKeyspaceEvents | quote }}
            - --databases
            - {{ .Values.redis.config.databases | quote }}
            {{- if eq .Values.redis.config.save "" }}
            - --save
            - ""
            {{- end }}
            {{- if .Values.redis.auth.enabled }}
            - --requirepass
            - {{ .Values.redis.auth.password | quote }}
            {{- end }}
          
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          
          volumeMounts:
            - name: redis-data
              mountPath: /data
      
      volumes:
        - name: redis-data
          emptyDir: {}  # Use persistent volume for production
{{- end }}