{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "barakah-fund.fullname" . }}-keycloak
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.ports.http }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: management
  selector:
    {{- include "barakah-fund.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
{{- end }}  