apiVersion: v1
kind: ConfigMap
metadata:
    name: kafka-config
    namespace: barakah-fund
data:
    KAFKA_ENABLE_KRAFT: "yes"
    KAFKA_CFG_PROCESS_ROLES: "broker,controller"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service.barakah-fund.svc.cluster.local:9092"
    KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-service.barakah-fund.svc.cluster.local:9093"
    KAFKA_CFG_NODE_ID: "1"
    KAFKA_KRAFT_CLUSTER_ID: "diz6IS9WQDmzQAF_gJVD7Q"

    KAFKA_CFG_BROKER_ID: "1"
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_CFG_NUM_PARTITIONS: "3"
    KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
    KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
    KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"

    KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
    KAFKA_CFG_LOG_RETENTION_HOURS: "168"
    KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824"
    KAFKA_CFG_LOG_SEGMENT_BYTES: "268435456"
    KAFKA_CFG_LOG_CLEANUP_POLICY: "delete"

    KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
    KAFKA_CFG_MESSAGE_MAX_BYTES: "1000000"
    KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: "1048576"

    KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: "102400"
    KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
    KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: "104857600"

    ALLOW_PLAINTEXT_LISTENER: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka
    namespace: barakah-fund
    labels:
        app: kafka
spec:
    replicas: 1
    selector:
        matchLabels:
            app: kafka
    template:
        metadata:
            labels:
                app: kafka
        spec:
            containers:
            - name: kafka
              image: confluentinc/cp-kafka:7.5.0
              ports:
              - containerPort: 9092
                name: kafka
              - containerPort: 9093
                name: controller
              env:
              - name: KAFKA_NODE_ID
                value: "1"
              - name: KAFKA_PROCESS_ROLES
                value: "broker,controller"
              - name: KAFKA_CONTROLLER_QUORUM_VOTERS
                value: "1@localhost:9093"
              - name: KAFKA_LISTENERS
                value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093"
              - name: KAFKA_ADVERTISED_LISTENERS
                value: "PLAINTEXT://kafka-service:9092"
              - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
              - name: KAFKA_CONTROLLER_LISTENER_NAMES
                value: "CONTROLLER"
              - name: KAFKA_INTER_BROKER_LISTENER_NAME
                value: "PLAINTEXT"
              - name: CLUSTER_ID
                value: "MkU3OEVBNTcwNTJENDM2Qk"
              - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
                value: "true"
              - name: KAFKA_NUM_PARTITIONS
                value: "3"
              - name: KAFKA_DEFAULT_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
                value: "1"
              - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
                value: "1"
              - name: KAFKA_LOG_RETENTION_HOURS
                value: "168"
              volumeMounts:
              - name: kafka-data
                mountPath: /var/lib/kafka/data
            volumes:
            - name: kafka-data
              emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-service
    namespace: barakah-fund
    labels:
        app: kafka
spec:
    type: ClusterIP
    ports:
        - port: 9092
          targetPort: 9092
          protocol: TCP
          name: kafka
    selector:
        app: kafka
    sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
    name: kafka-headless
    namespace: barakah-fund
    labels:
        app: kafka
spec:
    type: ClusterIP
    clusterIP: None
    ports:
        - port: 9092
          targetPort: 9092
          protocol: TCP
          name: kafka
        - port: 9093
          targetPort: 9093
          protocol: TCP
          name: controller
    selector:
        app: kafka
