apiVersion: v1
kind: Service
metadata:
    name: keycloak-service
    namespace: barakah-fund
    labels:
        app: keycloak
spec:
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: http
    selector:
        app: keycloak
    type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak
    namespace: barakah-fund
    labels:
        app: keycloak
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak
    template:
        metadata:
            labels:
                app: keycloak
        spec:
            containers:
                - name: keycloak
                  image: quay.io/keycloak/keycloak:24.0.5
                  args:
                      - start-dev
                      - --import-realm
                  env:
                      - name: KEYCLOAK_ADMIN
                        value: "admin"
                      - name: KEYCLOAK_ADMIN_PASSWORD
                        value: "admin123"
                      - name: KC_DB
                        value: "postgres"
                      - name: KC_DB_URL
                        value: "jdbc:postgresql://postgres-service:5432/barakah_main"
                      - name: KC_DB_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_USER
                      - name: KC_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_PASSWORD
                      - name: KC_HTTP_ENABLED
                        value: "true"
                      - name: KC_HOSTNAME_STRICT
                        value: "false"
                      - name: KC_PROXY_HEADERS
                        value: "xforwarded"
                  ports:
                      - name: http
                        containerPort: 8080
                  volumeMounts:
                      - name: realm-config
                        mountPath: /opt/keycloak/data/import
                        readOnly: true
                  startupProbe:
                      httpGet:
                          path: /realms/master
                          port: 8080
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      failureThreshold: 30
                  readinessProbe:
                      httpGet:
                          path: /realms/master
                          port: 8080
                      initialDelaySeconds: 120
                      periodSeconds: 10
                      failureThreshold: 10
                  livenessProbe:
                      httpGet:
                          path: /realms/master
                          port: 8080
                      initialDelaySeconds: 180
                      periodSeconds: 30
                      failureThreshold: 5
                  resources:
                      limits:
                          cpu: 1000m
                          memory: 1Gi
                      requests:
                          cpu: 500m
                          memory: 512Mi
            volumes:
                - name: realm-config
                  configMap:
                      name: keycloak-realm-config
