apiVersion: v1
kind: Namespace
metadata:
    name: barakah-fund
    labels:
        name: barakah-fund
        monitoring: enabled

---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring
    labels:
        name: monitoring
