apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: barakah-fund
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15-alpine
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: POSTGRES_DB
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_INITDB_ARGS
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: POSTGRES_INITDB_ARGS
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                      - name: init-scripts
                        mountPath: /docker-entrypoint-initdb.d
                        readOnly: true
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  readinessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - barakah_admin
                              - -d
                              - barakah_main
                      initialDelaySeconds: 15
                      periodSeconds: 5
                  livenessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - barakah_admin
                              - -d
                              - barakah_main
                      initialDelaySeconds: 30
                      periodSeconds: 10
            volumes:
                - name: postgres-storage
                  emptyDir: {} 
                - name: init-scripts
                  configMap:
                      name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: barakah-fund
    labels:
        app: postgres
spec:
    type: ClusterIP
    ports:
        - port: 5432
          targetPort: 5432
          protocol: TCP
    selector:
        app: postgres
