apiVersion: v1
kind: ServiceAccount
metadata:
    name: spring-cloud-kubernetes
    namespace: barakah-fund
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: spring-cloud-kubernetes
rules:
    - apiGroups: [""]
      resources: ["services", "endpoints", "configmaps", "pods"]
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: spring-cloud-kubernetes
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: spring-cloud-kubernetes
subjects:
    - kind: ServiceAccount
      name: spring-cloud-kubernetes
      namespace: barakah-fund