 spring:
     application:
         name: user-service

     cloud:
         config:
             enabled: false
         vault:
             enabled: ${VAULT_ENABLED:false}
             host: ${SPRING_CLOUD_VAULT_HOST:vault}
             port: ${SPRING_CLOUD_VAULT_PORT:8200}
             scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
             authentication: TOKEN
             token: ${SPRING_CLOUD_VAULT_TOKEN:root-token}

     datasource:
         url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:barakah_users}
         username: ${DB_USERNAME:barakah_user}
         password: ${DB_PASSWORD:barakah_user_password}
         driver-class-name: org.postgresql.Driver
         hikari:
             maximum-pool-size: 10
             minimum-idle: 5
             connection-timeout: 20000
             idle-timeout: 300000
             max-lifetime: 1200000

     jpa:
         hibernate:
             ddl-auto: update
             naming:
                 physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
         properties:
             hibernate:
                 dialect: org.hibernate.dialect.PostgreSQLDialect
                 show_sql: true
                 format_sql: true
                 use_sql_comments: true
                 jdbc:
                     batch_size: 20
                 order_inserts: true
                 order_updates: true
         show-sql: true
         open-in-view: false

     flyway:
         enabled: true
         baseline-on-migrate: true
         baseline-version: 0
         out-of-order: true
         validate-on-migrate: false
         locations: classpath:db/migration

     transaction:
         default-timeout: 30
     cache:
         type: redis
     redis:
         host: ${REDIS_HOST:redis}
         port: ${REDIS_PORT:6379}
         timeout: 2000
         database: ${REDIS_DATABASE:0}
         password: ${REDIS_PASSWORD:}
         lettuce:
             pool:
                 max-active: 8
                 max-wait: 100
                 max-idle: 8
                 min-idle: 0
             shutdown-timeout: 2000

 server:
     port: 8081
     servlet:
         context-path: /user-service
     error:
         include-message: always
         include-binding-errors: always
         include-stacktrace: on_param

 grpc:
     server:
         port: 9091
         enable-reflection: true
         max-inbound-message-size: 4MB
         max-outbound-message-size: 4MB

     client:
         user-service:
             address: discovery:///account-service
             negotiationType: plaintext
             keepAliveTime: 30s
             keepAliveTimeout: 5s
             keepAliveWithoutCalls: true
             maxRetryAttempts: 3
         transaction-service:
             address: discovery:///transaction-service
             negotiationType: plaintext
             keepAliveTime: 30s
             keepAliveTimeout: 5s
             keepAliveWithoutCalls: true
             maxRetryAttempts: 3

 eureka:
     client:
         service-url:
             defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
         eureka-server-connect-timeout-seconds: 5
         eureka-server-read-timeout-seconds: 8
         registry-fetch-interval-seconds: 30
         register-with-eureka: true
         fetch-registry: true
         healthcheck:
             enabled: true
     instance:
         prefer-ip-address: true
         hostname: ${HOSTNAME:localhost}
         instance-id: ${spring.application.name}:${random.value}
         lease-renewal-interval-in-seconds: 30
         lease-expiration-duration-in-seconds: 90
         metadata-map:
             grpc.port: 9091
             management.context-path: /user-service/actuator

 keycloak:
     auth-server-url: ${KEYCLOAK_URL:http://keycloak:8080}
     realm: ${KEYCLOAK_REALM:barakah}
     resource: ${KEYCLOAK_CLIENT_ID:user-service}
     credentials:
         secret: ${KEYCLOAK_CLIENT_SECRET:user-service-secret-change-me}
     admin:
         username: ${KEYCLOAK_ADMIN_USERNAME:admin}
         password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
         client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
     mock:
         enabled: ${KEYCLOAK_MOCK_ENABLED:true}

 management:
     endpoints:
         web:
             exposure:
                 include: "*"
             base-path: /actuator
     endpoint:
         health:
             show-details: always
             show-components: always
         metrics:
             enabled: true
         env:
             enabled: true
     health:
         eureka:
             enabled: true
         db:
             enabled: true
     metrics:
         export:
             prometheus:
                 enabled: true

 logging:
     level:
         com.barakah: DEBUG
         org.springframework.cloud.gateway: DEBUG
         io.grpc: INFO
         net.devh: DEBUG

 app:
     security:
         cors:
             allowed-origins: "http://localhost:3000,http://localhost:4200,http://localhost:8080"
             allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
             allowed-headers: "*"
             allow-credentials: true
             max-age: 3600
         jwt:
             secret: ${JWT_SECRET:dev-secret-key-change-in-production}
             expiration: ${JWT_EXPIRATION:86400000}

     user:
         default-role: USER
         password:
             min-length: 8
             require-special-chars: true
         registration:
             email-verification-required: false
             auto-approve: true

     services:
         auth-service:
             url: http://localhost:8082
             timeout: 5000
         transaction-service:
             url: http://localhost:8083
             timeout: 5000
         notification-service:
             url: http://localhost:8084
             timeout: 3000

 barakah:
     rate-limiting:
         enabled: ${features.rate-limiting:true}
         http:
             enabled: true
         grpc:
             enabled: true

         default:
             limit: 100
             duration-seconds: 60

 features:
     email-verification: false
     sms-verification: false
     audit-logging: true
     rate-limiting: true
     cache-enabled: true
