server:
    port: 8888

spring:
    application:
        name: config-server
    
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:vault,security}
    
    cloud:
        config:
            server:
                vault:
                    enabled: ${VAULT_ENABLED:true}
                    host: ${SPRING_CLOUD_VAULT_HOST:localhost}
                    port: ${SPRING_CLOUD_VAULT_PORT:8200}
                    scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
                    backend: secret
                    default-key: application
                    profile-separator: '/'
                    token: ${SPRING_CLOUD_VAULT_TOKEN:root-token}
                    kv-version: 2
                native:
                    search-locations: ${CONFIG_SEARCH_LOCATIONS:classpath:/config/,file:/app/config/}
                bootstrap: false
                accept-empty: true
        vault:
            enabled: ${VAULT_ENABLED:true}
            host: ${SPRING_CLOUD_VAULT_HOST:localhost}
            port: ${SPRING_CLOUD_VAULT_PORT:8200}
            scheme: ${SPRING_CLOUD_VAULT_SCHEME:http}
            authentication: TOKEN
            token: ${SPRING_CLOUD_VAULT_TOKEN:root-token}
            kv:
                enabled: true
                backend: secret
                profile-separator: '/'
                default-context: config-server
                application-name: config-server
            config:
                lifecycle:
                    enabled: true

    security:
        user:
            name: ${CONFIG_SERVER_USERNAME:config-user}
            password: ${CONFIG_SERVER_PASSWORD:config-pass}
            roles: CONFIG_ADMIN


management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        health:
            show-details: always
            show-components: always
        metrics:
            enabled: true
        env:
            enabled: true

logging:
    level:
        org.springframework.cloud.config: DEBUG
        org.springframework.vault: DEBUG
        com.barakah: DEBUG
