spring:
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:barakah_transactions}
        username: ${POSTGRES_USER:barakah_user}
        password: ${POSTGRES_PASSWORD:change-me}

grpc:
    server:
        port: ${GRPC_PORT:9093}
    client:
        account-service:
            address: ${ACCOUNT_SERVICE_HOST:account-service}:${ACCOUNT_SERVICE_GRPC_PORT:9092}
        user-service:
            address: ${USER_SERVICE_HOST:user-service}:${USER_SERVICE_GRPC_PORT:9091}

eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
    instance:
        hostname: ${HOSTNAME:transaction-service}

keycloak:
    auth-server-url: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8080}
    realm: ${KEYCLOAK_REALM:barakah}
    resource: ${KEYCLOAK_CLIENT_ID:transaction-service}
    credentials:
        secret: ${KEYCLOAK_CLIENT_SECRET:change-me}

app:
    services:
        account-service:
            url: http://${ACCOUNT_SERVICE_HOST:account-service}:${ACCOUNT_SERVICE_PORT:8082}
        user-service:
            url: http://${USER_SERVICE_HOST:user-service}:${USER_SERVICE_PORT:8081}
        notification-service:
            url: http://${NOTIFICATION_SERVICE_HOST:notification-service}:${NOTIFICATION_SERVICE_PORT:8084}

logging:
    level:
        com.barakah: ${LOG_LEVEL_APP:INFO}
        com.barakah.transaction: ${LOG_LEVEL_TRANSACTION:DEBUG}
    file:
        name: ${LOG_FILE:/app/logs/transaction-service.log}

spring:
    redis:
        host: ${REDIS_HOST:redis}
        port: ${REDIS_PORT:6379}
        password: ${REDIS_PASSWORD:}

kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    consumer:
        group-id: ${KAFKA_CONSUMER_GROUP:transaction-service}