apiVersion: v1
kind: Secret
metadata:
  name: {{ include "barakah-fund.fullname" . }}-secret
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
type: Opaque
data:
  
  {{- if .Values.postgresql.enabled }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | default "changeme123" | b64enc | quote }}
  {{- end }}
  
  
  JWT_SECRET: {{ .Values.security.jwtSecret | b64enc | quote }}
  
  
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}