{{- if or .Values.userService.enabled .Values.accountService.enabled .Values.transactionService.enabled .Values.notificationService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "barakah-fund.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "barakah-fund.fullname" . }}-app
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared
rules:
# Permissions for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]

# Permissions for pod information (health checks, metrics)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Permissions for config and secrets (if needed for dynamic config)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# Limited secret access (only if absolutely necessary)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: 
    - {{ include "barakah-fund.fullname" . }}-config
    - {{ include "barakah-fund.fullname" . }}-secrets

# Permissions for custom resources (if using service mesh, etc.)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "barakah-fund.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "barakah-fund.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared
subjects:
- kind: ServiceAccount
  name: {{ include "barakah-fund.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "barakah-fund.fullname" . }}-app
  apiGroup: rbac.authorization.k8s.io
{{- end }}