apiVersion: apps/v1
kind: Deployment
metadata:
    name: eureka-server
    namespace: barakah-fund
    labels:
        app: eureka-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: eureka-server
    template:
        metadata:
            labels:
                app: eureka-server
        spec:
            containers:
                - name: eureka-server
                  image: barakah/eureka-server:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8761
                        name: http

                  envFrom:
                      - configMapRef:
                            name: spring-common-config
                      - configMapRef:
                            name: eureka-server-config

                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "200m"
                      limits:
                          memory: "512Mi"
                          cpu: "400m"

                  readinessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8761
                      initialDelaySeconds: 45
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3

                  livenessProbe:
                      httpGet:
                          path: /actuator/health
                          port: 8761
                      initialDelaySeconds: 60
                      periodSeconds: 15
                      timeoutSeconds: 5
                      failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
    name: eureka-server
    namespace: barakah-fund
    labels:
        app: eureka-server
spec:
    type: ClusterIP
    ports:
        - port: 8761
          targetPort: 8761
          protocol: TCP
          name: http
    selector:
        app: eureka-server
