apiVersion: apps/v1
kind: Deployment
metadata:
    name: gateway-service
    namespace: barakah-fund
    labels:
        app: gateway-service
spec:
    replicas: 2
    selector:
        matchLabels:
            app: gateway-service
    template:
        metadata:
            labels:
                app: gateway-service
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8070"
                prometheus.io/path: "/actuator/prometheus"
        spec:
            serviceAccountName: spring-cloud-kubernetes # ✅ Add service account
            containers:
                - name: gateway-service
                  image: barakah/gateway-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8070
                        name: http
                      - containerPort: 9090
                        name: grpc

                  envFrom:
                      - configMapRef:
                            name: spring-common-config
                      - configMapRef:
                            name: gateway-service-config

                  env:
                      - name: KEYCLOAK_CREDENTIALS_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: KEYCLOAK_CLIENT_SECRET
                                optional: true

                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "250m"
                      limits:
                          memory: "1Gi"
                          cpu: "500m"

                  readinessProbe:
                      httpGet:
                          path: /actuator/health/readiness
                          port: 8070
                      initialDelaySeconds: 60
                      periodSeconds: 10
                      timeoutSeconds: 5
                      failureThreshold: 3

                  livenessProbe:
                      httpGet:
                          path: /actuator/health/liveness
                          port: 8070
                      initialDelaySeconds: 90
                      periodSeconds: 15
                      timeoutSeconds: 5
                      failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
    name: gateway-service
    namespace: barakah-fund
    labels:
        app: gateway-service
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 8070
          targetPort: 8070
          protocol: TCP
        - name: grpc
          port: 9090
          targetPort: 9090
          protocol: TCP
    selector:
        app: gateway-service
