eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
    ip-address: ${EUREKA_IP:eureka-server}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.netflix.eureka: INFO
    root: WARN