spring:
    application:
        name: user-service

    datasource:
        url: jdbc:postgresql://postgres:5432/barakah_users
        username: barakah_user
        password: barakah_password
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            idle-timeout: 300000
            connection-timeout: 20000
            leak-detection-threshold: 60000

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: false
                show_sql: false
                jdbc:
                    time_zone: UTC
                order_inserts: true
                order_updates: true
                batch_size: 25
        show-sql: false

    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
        validate-on-migrate: true
        clean-disabled: true

    cloud:
        config:
            enabled: true
            fail-fast: true
            retry:
                initial-interval: 1000
                max-attempts: 6
                max-interval: 2000
                multiplier: 1.1

server:
    port: 8081
    servlet:
        context-path: /user-service
    shutdown: graceful

grpc:
    server:
        port: 9091
        enable-reflection: true
        max-message-size: 4MB
        max-header-list-size: 8192

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
        healthcheck:
            enabled: true
    instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
        metadata-map:
            grpc.port: 9091
            management.context-path: /user-service/actuator

keycloak:
    auth-server-url: http://keycloak:8080
    realm: barakah
    resource: user-service
    credentials:
        secret: user-service-secret-change-me
    admin:
        username: admin
        password: admin
        client-id: admin-cli
    token:
        cache:
            enabled: true
            size: 1000
            ttl: 300

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus,flyway
            base-path: /actuator
    endpoint:
        health:
            show-details: always
            probes:
                enabled: true
    health:
        db:
            enabled: true
        diskspace:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
    info:
        env:
            enabled: true
        git:
            mode: full

logging:
    level:
        com.barakah: INFO
        com.barakah.user: DEBUG
        org.springframework.cloud: INFO
        org.springframework.security: INFO
        org.keycloak: INFO
        org.flywaydb: INFO
        io.grpc: INFO
    pattern:
        file: "%d{ISO8601} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file:
        name: logs/user-service.log
        max-size: 100MB
        max-history: 30

app:
    user:
        default-role: USER
        max-login-attempts: 5
        account-lock-duration: PT30M
        password:
            min-length: 8
            require-uppercase: true
            require-lowercase: true
            require-numbers: true
            require-special-chars: true
    security:
        jwt:
            expiration: 3600
            refresh-expiration: 86400
        cors:
            allowed-origins: "*"
            allowed-methods: GET,POST,PUT,DELETE,OPTIONS
            allowed-headers: "*"
