spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/barakah_users
        username: barakah_user
        password: barakah_password

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
        show-sql: true

server:
    port: 8081

grpc:
    server:
        port: 9091

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

keycloak:
    auth-server-url: http://localhost:8080

logging:
    level:
        com.barakah: DEBUG
        com.barakah.user: TRACE
        org.springframework.security: DEBUG
        org.keycloak: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
    security:
        cors:
            allowed-origins: "http://localhost:3000,http://localhost:4200"
